"use strict";

const fs = require("fs");
const os = require("os");
const path = require("path");
const {
  assert,
  assertExit,
  assertIncludes,
  assertNotIncludes,
  assertFileExists,
  assertFileMissing,
} = require("./lib/assertions");
const {
  run,
  runNode,
  writeFile,
  readJson,
  writeJson,
  makeTempRepo,
  latestRunId,
  taskFixture,
  writeTask,
  readWorktrees,
  cleanupRepo,
} = require("./lib/temp-repo");

const cewpRoot = path.resolve(__dirname, "..", "..");
const cewpCli = path.join(cewpRoot, "bin", "cewp.js");
const packageJson = readJson(path.join(cewpRoot, "package.json"));
const results = [];
const tempRepos = [];

function pass(label) {
  results.push({ label, status: "PASS" });
  console.log(`[PASS] ${label}`);
}

function fail(label, error) {
  results.push({ label, status: "FAIL", error });
  console.log(`[FAIL] ${label}`);
  console.log(String(error && error.stack ? error.stack : error).slice(0, 4000));
}

async function step(label, fn) {
  try {
    await fn();
    pass(label);
  } catch (error) {
    fail(label, error);
    throw error;
  }
}

function cewp(args, cwd) {
  return runNode(cewpCli, args, cwd);
}

function cewpWithEnv(args, cwd, env) {
  return runNode(cewpCli, args, cwd, { env });
}

function makeFakeCodexShim() {
  const fakeRoot = fs.mkdtempSync(path.join(os.tmpdir(), "cewp-fake-codex-"));
  const scriptPath = path.join(fakeRoot, "fake-codex.js");
  writeFile(scriptPath, `#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");

const args = process.argv.slice(2);
if (args[0] !== "exec") {
  console.error("fake codex only supports exec");
  process.exit(2);
}

function valueAfter(flag) {
  const index = args.indexOf(flag);
  return index === -1 ? undefined : args[index + 1];
}

const worktree = valueAfter("--cd");
const lastMessage = valueAfter("--output-last-message");
const prompt = args[args.length - 1] || "";
const roleMatch = prompt.match(/^Role:\\s*(worker-a|worker-b)\\b/m);
const taskMatch = prompt.match(/^Task:\\s*([^\\s]+)\\b/m);
const role = roleMatch ? roleMatch[1] : "worker-a";
const task = taskMatch ? taskMatch[1] : "unknown-task";
const changedFile = role === "worker-b" ? "docs/install.md" : "README.md";

fs.mkdirSync(path.dirname(path.join(worktree, changedFile)), { recursive: true });
fs.writeFileSync(path.join(worktree, changedFile), \`# Fake Codex \${role}\\n\\nTask \${task} changed \${changedFile}.\\n\`);

const outputRoot = path.join(worktree, ".cewp-worker-output");
fs.mkdirSync(outputRoot, { recursive: true });
fs.writeFileSync(
  path.join(outputRoot, \`\${role}-report.md\`),
  \`# Worker Report\\n\\nRole: \${role}\\nTask: \${task}\\nStatus: ready_for_review\\n\\n## Summary\\nFake codex lifecycle smoke.\\n\\n## Changed Files\\n- \${changedFile}\\n\\n## Commands Run\\n- fake codex exec\\n\\n## Test Results\\n- not run by fake shim\\n\\n## Risks\\n- none\\n\\n## Handoff Notes\\n- generated by harness fake codex\\n\`,
);
fs.writeFileSync(
  path.join(outputRoot, \`\${role}-events.jsonl\`),
  JSON.stringify({ role, task, event: "fake-codex-completed", changedFile }) + "\\n",
);

if (lastMessage) {
  fs.mkdirSync(path.dirname(lastMessage), { recursive: true });
  fs.writeFileSync(lastMessage, \`Fake codex completed \${role} for \${task}.\\n\`);
}

console.log(\`fake codex stdout: \${role} \${task}\`);
console.error(\`fake codex stderr: \${role} \${task}\`);
`);

  return {
    fakeRoot,
    env: {
      ...process.env,
      CEWP_CODEX_EXEC_COMMAND: process.execPath,
      CEWP_CODEX_EXEC_PREFIX_ARGS: JSON.stringify([scriptPath]),
    },
  };
}

function initHarnessRun(repoRoot, tasks) {
  const init = cewp(["run", "init", "--workers", "2", "--reviewer"], repoRoot);
  assertExit(init, 0, "run init");

  const runId = latestRunId(repoRoot);
  assert(runId, "run init did not create a run id");

  const repoName = path.basename(repoRoot);
  for (const task of tasks(runId, repoName)) {
    writeTask(repoRoot, runId, task);
  }

  return runId;
}

function createTwoTaskRun(repoRoot) {
  return initHarnessRun(repoRoot, (runId, repoName) => [
    taskFixture({
      id: "task-001",
      assignedRole: "worker-a",
      allowedFiles: ["README.md"],
      forbiddenFiles: ["package.json", ".env", ".agents/skills/**", "bin/cewp.js"],
      mission: "Update README.md only.",
      runId,
      repoName,
    }),
    taskFixture({
      id: "task-002",
      assignedRole: "worker-b",
      allowedFiles: ["docs/install.md"],
      forbiddenFiles: ["package.json", ".env", ".agents/skills/**", "bin/cewp.js"],
      mission: "Update docs/install.md only.",
      runId,
      repoName,
    }),
  ]);
}

function commitInWorktree(worktreePath, relativeFile, content, message) {
  writeFile(path.join(worktreePath, relativeFile), content);
  assertExit(run("git", ["add", relativeFile], { cwd: worktreePath }), 0, `git add ${relativeFile}`);
  assertExit(run("git", ["commit", "-m", message], { cwd: worktreePath }), 0, `git commit ${relativeFile}`);
}

function makeReport(repoRoot, runId, role, changedFile) {
  writeFile(
    path.join(repoRoot, ".cewp", "runs", runId, "reports", `${role}-report.md`),
    `# Worker Report\n\nRole: ${role}\nStatus: ready_for_review\n\n## Changed Files\n- ${changedFile}\n`,
  );
}

function setupFakeAdapterRun(repoRoot) {
  const runId = createTwoTaskRun(repoRoot);
  assertExit(cewp(["run", "worktrees", "create", "--run", runId], repoRoot), 0, "fake adapter worktrees create");
  assertExit(cewp(["run", "dispatch", "prompts", "--run", runId], repoRoot), 0, "fake adapter dispatch prompts");
  assertExit(cewp(["policy", "set", "full-authority"], repoRoot), 0, "fake adapter policy full-authority");
  return {
    runId,
    registry: readWorktrees(repoRoot, runId),
  };
}

function assertFakeWorkerLifecycle(repoRoot, runId, registry, role, changedFile) {
  const worker = registry.worktrees.find((entry) => entry.assignedRole === role);
  assert(worker, `${role} registry entry missing`);

  assertFileExists(path.join(worker.path, ".cewp-worker-output", `${role}-report.md`), `${role} local report`);
  assertFileExists(path.join(worker.path, ".cewp-worker-output", `${role}-events.jsonl`), `${role} local events`);
  assertFileExists(path.join(repoRoot, ".cewp", "runs", runId, "reports", `${role}-report.md`), `${role} copied report`);
  assertFileExists(path.join(repoRoot, ".cewp", "runs", runId, "adapter-output", `${role}-last-message.md`), `${role} last message`);
  assertFileExists(path.join(repoRoot, ".cewp", "runs", runId, "adapter-output", `${role}-stdout.log`), `${role} stdout log`);
  assertFileExists(path.join(repoRoot, ".cewp", "runs", runId, "adapter-output", `${role}-stderr.log`), `${role} stderr log`);

  const status = cewp(["run", "worktrees", "status", "--run", runId], repoRoot);
  assertExit(status, 0, `${role} post fake worktrees status`);
  assertIncludes(status.stdout, changedFile, `${role} changed file visible`);
  assertIncludes(status.stdout, "Scope: OK", `${role} scope ok`);

  const report = fs.readFileSync(path.join(repoRoot, ".cewp", "runs", runId, "reports", `${role}-report.md`), "utf8");
  assertIncludes(report, "Fake codex lifecycle smoke.", `${role} copied report content`);
}

function pruneFixture(repoRoot) {
  const runsRoot = path.join(repoRoot, ".cewp", "runs");
  fs.mkdirSync(runsRoot, { recursive: true });

  for (const runId of ["20260529-000001", "20260529-000002", "20260529-000003"]) {
    fs.mkdirSync(path.join(runsRoot, runId), { recursive: true });
    writeFile(path.join(runsRoot, runId, "run.json"), "{}\n");
  }

  fs.mkdirSync(path.join(runsRoot, "not-a-run"), { recursive: true });
}

async function main() {
  console.log("CEWP Harness Smoke\n");

  let coordinatorRepo;
  let negativeRepo;
  let pruneRepo;
  let policyRepo;

  try {
    await step("cli help", () => {
      assertExit(cewp(["--help"], cewpRoot), 0, "cewp --help");
    });

    await step("doctor", () => {
      assertExit(cewp(["doctor"], cewpRoot), 0, "cewp doctor");
    });

    await step("list", () => {
      assertExit(cewp(["list"], cewpRoot), 0, "cewp list");
    });

    await step("docs and dispatch wording", () => {
      const dispatchPlan = fs.readFileSync(path.join(cewpRoot, "src", "run", "dispatch", "plan.js"), "utf8");
      const dispatchStart = fs.readFileSync(path.join(cewpRoot, "src", "run", "dispatch", "start.js"), "utf8");

      assertNotIncludes(dispatchPlan, "codex-exec: planned, not implemented", "dispatch plan wording");
      assertNotIncludes(dispatchStart, "codex-exec: planned, not implemented", "dispatch start wording");
    });

    await step("operator policy", () => {
      policyRepo = makeTempRepo("cewp-harness-policy-");
      tempRepos.push(policyRepo);
      const showDefault = cewp(["policy", "show"], policyRepo);
      assertExit(showDefault, 0, "policy show default");
      assertIncludes(showDefault.stdout, "Mode: safe (default)", "default policy mode");

      const blockedWorkers = cewp(["run", "dispatch", "exec", "workers", "--adapter", "codex-exec", "--yes"], policyRepo);
      assertExit(blockedWorkers, 1, "safe policy blocks workers");
      assertIncludes(blockedWorkers.stderr, "operator policy blocks dispatch worker execution", "workers policy block");

      const blockedPipeline = cewp(["run", "dispatch", "pipeline", "--adapter", "codex-exec", "--yes"], policyRepo);
      assertExit(blockedPipeline, 1, "safe policy blocks pipeline");
      assertIncludes(blockedPipeline.stderr, "operator policy blocks dispatch pipeline execution", "pipeline policy block");

      pruneFixture(policyRepo);
      const pruneDryRun = cewp(["run", "prune", "--keep", "2"], policyRepo);
      assertExit(pruneDryRun, 0, "policy allows prune dry-run");
      const blockedPrune = cewp(["run", "prune", "--keep", "2", "--yes"], policyRepo);
      assertExit(blockedPrune, 1, "safe policy blocks prune deletion");
      assertIncludes(blockedPrune.stderr, "operator policy blocks cleanup/prune deletion", "prune policy block");

      const setFull = cewp(["policy", "set", "full-authority"], policyRepo);
      assertExit(setFull, 0, "policy set full-authority");
      const policyPath = path.join(policyRepo, ".cewp", "policy.json");
      assertFileExists(policyPath, "policy file");
      const policy = readJson(policyPath);
      assert(policy.mode === "full-authority", "expected full-authority policy");
      assert(policy.authority.runWorkers === true, "full-authority should allow workers");
      assert(policy.authority.push === false, "push should remain disabled by default");

      const reset = cewp(["policy", "reset"], policyRepo);
      assertExit(reset, 0, "policy reset");
      const resetPolicy = readJson(policyPath);
      assert(resetPolicy.mode === "safe", "policy reset should write safe mode");
    });

    coordinatorRepo = makeTempRepo("cewp-harness-flow-");
    tempRepos.push(coordinatorRepo);
    let flowRunId;
    let flowRegistry;

    await step("temp repo init", () => {
      flowRunId = createTwoTaskRun(coordinatorRepo);
      assertFileExists(path.join(coordinatorRepo, ".cewp", "runs", flowRunId, "run.json"), "run.json");
    });

    await step("worktrees create", () => {
      const create = cewp(["run", "worktrees", "create", "--run", flowRunId], coordinatorRepo);
      assertExit(create, 0, "worktrees create");
      flowRegistry = readWorktrees(coordinatorRepo, flowRunId);
      assert(flowRegistry.worktrees.length === 2, "expected two registered worktrees");
      for (const entry of flowRegistry.worktrees) {
        assert(entry.baseCommit, `${entry.taskId} missing baseCommit`);
        assert(fs.existsSync(entry.path), `${entry.taskId} worktree path missing`);
      }
    });

    await step("worktrees status", () => {
      const status = cewp(["run", "worktrees", "status", "--run", flowRunId], coordinatorRepo);
      assertExit(status, 0, "worktrees status");
      assertIncludes(status.stdout, "Scope: OK", "worktrees status");
    });

    await step("committed allowed changes visible", () => {
      const workerA = flowRegistry.worktrees.find((entry) => entry.assignedRole === "worker-a");
      const workerB = flowRegistry.worktrees.find((entry) => entry.assignedRole === "worker-b");
      commitInWorktree(workerA.path, "README.md", "# Harness Repo\n\nWorker A committed change.\n", "test: worker a docs");
      commitInWorktree(workerB.path, "docs/install.md", "# Install\n\nWorker B committed change.\n", "test: worker b docs");
      makeReport(coordinatorRepo, flowRunId, "worker-a", "README.md");
      makeReport(coordinatorRepo, flowRunId, "worker-b", "docs/install.md");

      const status = cewp(["run", "worktrees", "status", "--run", flowRunId], coordinatorRepo);
      assertExit(status, 0, "worktrees status after commits");
      assertIncludes(status.stdout, "Committed since baseCommit:", "committed changes header");
      assertIncludes(status.stdout, "README.md", "worker-a committed README");
      assertIncludes(status.stdout, "docs/install.md", "worker-b committed docs");
      assertIncludes(status.stdout, "Scope: OK", "committed allowed scope");

      const collect = cewp(["run", "collect", "--run", flowRunId], coordinatorRepo);
      assertExit(collect, 0, "collect");
      const packetPath = path.join(coordinatorRepo, ".cewp", "runs", flowRunId, "review-packets", "review-packet.md");
      assertFileExists(packetPath, "review packet");
      const packet = fs.readFileSync(packetPath, "utf8");
      assertIncludes(packet, "Committed branch changes", "review packet committed section");
      assertIncludes(packet, "README.md", "review packet README");
      assertIncludes(packet, "docs/install.md", "review packet docs");
    });

    negativeRepo = makeTempRepo("cewp-harness-negative-");
    tempRepos.push(negativeRepo);

    await step("committed outside allowed detected", () => {
      const runId = initHarnessRun(negativeRepo, (fixtureRunId, repoName) => [
        taskFixture({
          id: "task-001",
          assignedRole: "worker-a",
          allowedFiles: ["a.txt"],
          forbiddenFiles: ["package.json", ".env", ".agents/skills/**", "bin/cewp.js"],
          mission: "Only a.txt is allowed.",
          runId: fixtureRunId,
          repoName,
        }),
      ]);
      assertExit(cewp(["run", "worktrees", "create", "--run", runId], negativeRepo), 0, "negative worktree create");
      const registry = readWorktrees(negativeRepo, runId);
      const workerA = registry.worktrees.find((entry) => entry.assignedRole === "worker-a");
      commitInWorktree(workerA.path, "secret.txt", "committed secret\n", "test: forbidden outside scope");

      const status = cewp(["run", "worktrees", "status", "--run", runId], negativeRepo);
      assertExit(status, 0, "negative worktrees status");
      assertIncludes(status.stdout, "secret.txt", "outside allowed committed file");
      assertIncludes(status.stdout, "changed file outside allowedFiles: secret.txt", "outside allowed warning");
    });

    await step("worker scope guardrails", () => {
      const scopeRepo = makeTempRepo("cewp-harness-scope-");
      tempRepos.push(scopeRepo);
      const runId = initHarnessRun(scopeRepo, (fixtureRunId, repoName) => [
        taskFixture({
          id: "task-001",
          assignedRole: "worker-a",
          allowedFiles: [],
          forbiddenFiles: ["package.json", ".env", ".agents/skills/**", "bin/cewp.js"],
          mission: "Empty allowedFiles should block real worker execution.",
          runId: fixtureRunId,
          repoName,
        }),
        taskFixture({
          id: "task-002",
          assignedRole: "worker-b",
          allowedFiles: ["docs/install.md"],
          forbiddenFiles: ["package.json", ".env", ".agents/skills/**", "bin/cewp.js"],
          mission: "Valid worker task.",
          runId: fixtureRunId,
          repoName,
        }),
      ]);

      assertExit(cewp(["run", "worktrees", "create", "--run", runId], scopeRepo), 0, "scope worktrees create");
      assertExit(cewp(["run", "dispatch", "prompts", "--run", runId], scopeRepo), 0, "scope dispatch prompts");
      assertExit(cewp(["policy", "set", "full-authority"], scopeRepo), 0, "scope policy full-authority");

      const dryRun = cewp(["run", "dispatch", "exec", "worker-a", "--run", runId, "--adapter", "codex-exec", "--dry-run"], scopeRepo);
      assertExit(dryRun, 0, "empty allowedFiles worker dry-run");
      assertIncludes(dryRun.stdout, "real worker execution requires an explicit file scope", "dry-run allowedFiles warning");

      const actual = cewp(["run", "dispatch", "exec", "worker-a", "--run", runId, "--adapter", "codex-exec", "--yes"], scopeRepo);
      assertExit(actual, 1, "empty allowedFiles worker actual");
      assertIncludes(actual.stdout, "task task-001 has no allowedFiles", "actual allowedFiles failure");

      const workers = cewp(["run", "dispatch", "exec", "workers", "--run", runId, "--adapter", "codex-exec", "--yes"], scopeRepo);
      assertExit(workers, 1, "empty allowedFiles workers actual");
      assertIncludes(workers.stdout, "worker-b: SKIPPED", "sequential worker-b skipped");

      const check = cewp(["run", "dispatch", "check", "--run", runId], scopeRepo);
      assertExit(check, 1, "dispatch check empty allowedFiles");
      assertIncludes(check.stdout, "allowedFiles is empty; real worker execution requires an explicit file scope", "dispatch check allowedFiles fail");
    });

    await step("fake codex worker lifecycle", () => {
      const fake = makeFakeCodexShim();
      const fakeRepo = makeTempRepo("cewp-harness-fake-worker-");
      tempRepos.push(fakeRepo);

      try {
        const { runId, registry } = setupFakeAdapterRun(fakeRepo);
        const exec = cewpWithEnv([
          "run",
          "dispatch",
          "exec",
          "worker-a",
          "--run",
          runId,
          "--adapter",
          "codex-exec",
          "--yes",
        ], fakeRepo, fake.env);

        assertExit(exec, 0, "fake worker-a dispatch exec");
        assertIncludes(exec.stdout, "Status: PASS", "fake worker-a pass");
        assertIncludes(exec.stdout, "Scope: OK", "fake worker-a scope");
        assertIncludes(exec.stdout, "Report: copied", "fake worker-a report copy");
        assertFakeWorkerLifecycle(fakeRepo, runId, registry, "worker-a", "README.md");
      } finally {
        fs.rmSync(fake.fakeRoot, { recursive: true, force: true });
      }
    });

    await step("fake codex workers lifecycle", () => {
      const fake = makeFakeCodexShim();
      const fakeRepo = makeTempRepo("cewp-harness-fake-workers-");
      tempRepos.push(fakeRepo);

      try {
        const { runId, registry } = setupFakeAdapterRun(fakeRepo);
        const exec = cewpWithEnv([
          "run",
          "dispatch",
          "exec",
          "workers",
          "--run",
          runId,
          "--adapter",
          "codex-exec",
          "--yes",
        ], fakeRepo, fake.env);

        assertExit(exec, 0, "fake workers dispatch exec");
        assertIncludes(exec.stdout, "worker-a: PASS", "fake workers worker-a pass");
        assertIncludes(exec.stdout, "worker-b: PASS", "fake workers worker-b pass");
        assertIncludes(exec.stdout, "Overall: PASS", "fake workers overall pass");
        assertFakeWorkerLifecycle(fakeRepo, runId, registry, "worker-a", "README.md");
        assertFakeWorkerLifecycle(fakeRepo, runId, registry, "worker-b", "docs/install.md");

        const collect = cewp(["run", "collect", "--run", runId], fakeRepo);
        assertExit(collect, 0, "fake workers collect");
        const packetPath = path.join(fakeRepo, ".cewp", "runs", runId, "review-packets", "review-packet.md");
        assertFileExists(packetPath, "fake workers review packet");
        const packet = fs.readFileSync(packetPath, "utf8");
        assertIncludes(packet, "Fake codex lifecycle smoke.", "fake workers packet includes reports");
        assertIncludes(packet, "README.md", "fake workers packet README");
        assertIncludes(packet, "docs/install.md", "fake workers packet docs");
      } finally {
        fs.rmSync(fake.fakeRoot, { recursive: true, force: true });
      }
    });

    await step("parallel allowedFiles overlap", () => {
      const { getAllowedFilesOverlap } = require("../../src/lib/scope-check");
      assert(
        getAllowedFilesOverlap({ allowedFiles: ["docs/**"] }, { allowedFiles: ["docs/install.md"] }).length > 0,
        "docs/** should overlap docs/install.md",
      );
      assert(
        getAllowedFilesOverlap({ allowedFiles: ["docs/install.md"] }, { allowedFiles: ["docs/**"] }).length > 0,
        "docs/install.md should overlap docs/**",
      );
      assert(
        getAllowedFilesOverlap({ allowedFiles: ["docs/**"] }, { allowedFiles: ["docs/**"] }).length > 0,
        "same broad pattern should overlap",
      );
      assert(
        getAllowedFilesOverlap({ allowedFiles: ["README.md"] }, { allowedFiles: ["README.md"] }).length > 0,
        "same file should overlap",
      );
      assert(
        getAllowedFilesOverlap({ allowedFiles: ["README.md"] }, { allowedFiles: ["docs/install.md"] }).length === 0,
        "independent files should not overlap",
      );
    });

    await step("target worktree policy", () => {
      const traversalRepo = makeTempRepo("cewp-harness-traversal-");
      tempRepos.push(traversalRepo);
      const traversalRunId = initHarnessRun(traversalRepo, (fixtureRunId, repoName) => {
        const task = taskFixture({
          id: "task-001",
          assignedRole: "worker-a",
          allowedFiles: ["README.md"],
          forbiddenFiles: ["package.json", ".env", ".agents/skills/**", "bin/cewp.js"],
          mission: "Traversal target should be rejected.",
          runId: fixtureRunId,
          repoName,
        });
        task.targetWorktree = "../outside";
        return [task];
      });
      const traversalCreate = cewp(["run", "worktrees", "create", "--run", traversalRunId], traversalRepo);
      assertExit(traversalCreate, 1, "targetWorktree traversal rejected");
      assertIncludes(traversalCreate.stderr, "Unsafe targetWorktree", "traversal rejection");

      const absoluteRepo = makeTempRepo("cewp-harness-absolute-");
      tempRepos.push(absoluteRepo);
      const externalPath = path.join(path.dirname(absoluteRepo), `outside-worktree-${Date.now()}`);
      const absoluteRunId = initHarnessRun(absoluteRepo, (fixtureRunId, repoName) => {
        const task = taskFixture({
          id: "task-001",
          assignedRole: "worker-a",
          allowedFiles: ["README.md"],
          forbiddenFiles: ["package.json", ".env", ".agents/skills/**", "bin/cewp.js"],
          mission: "Absolute external target should be rejected.",
          runId: fixtureRunId,
          repoName,
        });
        task.targetWorktree = externalPath;
        return [task];
      });
      const absoluteCreate = cewp(["run", "worktrees", "create", "--run", absoluteRunId], absoluteRepo);
      assertExit(absoluteCreate, 1, "absolute external targetWorktree rejected");
      assertIncludes(absoluteCreate.stderr, "External targetWorktree", "absolute external rejection");
      assertFileMissing(externalPath, "absolute external worktree");

      const managedRepo = makeTempRepo("cewp-harness-managed-absolute-");
      tempRepos.push(managedRepo);
      const managedRunId = initHarnessRun(managedRepo, (fixtureRunId, repoName) => {
        const task = taskFixture({
          id: "task-001",
          assignedRole: "worker-a",
          allowedFiles: ["README.md"],
          forbiddenFiles: ["package.json", ".env", ".agents/skills/**", "bin/cewp.js"],
          mission: "Managed absolute target should be accepted.",
          runId: fixtureRunId,
          repoName,
        });
        task.targetWorktree = path.resolve(managedRepo, "..", ".cewp-worktrees", repoName, fixtureRunId, "task-001");
        return [task];
      });
      const managedCreate = cewp(["run", "worktrees", "create", "--run", managedRunId], managedRepo);
      assertExit(managedCreate, 0, "managed absolute targetWorktree accepted");

      const registry = readWorktrees(managedRepo, managedRunId);
      const externalRegistryPath = path.join(path.dirname(managedRepo), `external-registry-${Date.now()}`);
      fs.mkdirSync(externalRegistryPath, { recursive: true });
      registry.worktrees[0].path = externalRegistryPath;
      writeJson(path.join(managedRepo, ".cewp", "runs", managedRunId, "worktrees.json"), registry);

      const check = cewp(["run", "dispatch", "check", "--run", managedRunId], managedRepo);
      assertExit(check, 1, "dispatch check external registry path");
      assertIncludes(check.stdout, "worktree path is outside CEWP-managed root", "external registry path warning");

      assertExit(cewp(["policy", "set", "full-authority"], managedRepo), 0, "managed repo full-authority");
      const cleanup = cewp(["run", "cleanup", "--run", managedRunId, "--yes"], managedRepo);
      assertExit(cleanup, 0, "cleanup external registry path");
      assertFileExists(externalRegistryPath, "cleanup must not remove external registry path");
      fs.rmSync(externalRegistryPath, { recursive: true, force: true });
    });

    await step("run prune", () => {
      pruneRepo = makeTempRepo("cewp-harness-prune-");
      tempRepos.push(pruneRepo);
      pruneFixture(pruneRepo);

      const oldRun = path.join(pruneRepo, ".cewp", "runs", "20260529-000001");
      const newestA = path.join(pruneRepo, ".cewp", "runs", "20260529-000002");
      const newestB = path.join(pruneRepo, ".cewp", "runs", "20260529-000003");
      const notRun = path.join(pruneRepo, ".cewp", "runs", "not-a-run");

      const dryRun = cewp(["run", "prune", "--keep", "2"], pruneRepo);
      assertExit(dryRun, 0, "prune dry-run");
      assertIncludes(dryRun.stdout, "Would remove", "prune dry-run output");
      assertFileExists(oldRun, "old run after dry-run");

      assertExit(cewp(["policy", "set", "full-authority"], pruneRepo), 0, "policy set full-authority for prune");
      const yes = cewp(["run", "prune", "--keep", "2", "--yes"], pruneRepo);
      assertExit(yes, 0, "prune --yes");
      assertFileMissing(oldRun, "old run after prune");
      assertFileExists(newestA, "newest run A after prune");
      assertFileExists(newestB, "newest run B after prune");
      assertFileExists(notRun, "non-run directory after prune");
    });

    await step("package surface", () => {
      const pack = run("npm", ["pack", "--dry-run"], { cwd: cewpRoot, timeout: 120000 });
      assertExit(pack, 0, "npm pack --dry-run");
      assert(packageJson.version === "0.2.0-beta.1", `unexpected package version: ${packageJson.version}`);
      assert(!pack.stdout.includes(".cewp/"), ".cewp/ should not be packed");
      assert(!pack.stdout.includes(".cewp-worktrees/"), ".cewp-worktrees/ should not be packed");
    });
  } finally {
    for (const repo of tempRepos.reverse()) {
      cleanupRepo(repo);
    }
  }

  const failed = results.filter((result) => result.status !== "PASS");
  console.log("");
  console.log(`Overall: ${failed.length === 0 ? "PASS" : "FAIL"}`);

  if (failed.length > 0) {
    process.exitCode = 1;
  }
}

main().catch(() => {
  process.exitCode = 1;
});
