"use strict";

const fs = require("fs");
const os = require("os");
const path = require("path");
const { writeFile } = require("./temp-repo");

const FAKE_ADAPTER_MODES = Object.freeze({
  PASS: "pass",
  SCOPE_VIOLATION: "scope-violation",
  WORKER_NONZERO: "worker-nonzero",
  REVIEWER_MISSING_DECISION: "reviewer-missing-decision",
  REVIEWER_REQUEST_CHANGES: "reviewer-request-changes",
});

const FAKE_OPENCODE_MODES = Object.freeze({
  PASS: "pass",
  UNEXPECTED_JSON: "unexpected-json",
  INVALID_JSON: "invalid-json",
  NONZERO: "nonzero",
  SILENT_NONZERO: "silent-nonzero",
  TIMEOUT: "timeout",
});

function createFakeCodexAdapter(mode = FAKE_ADAPTER_MODES.PASS) {
  const fakeRoot = fs.mkdtempSync(path.join(os.tmpdir(), "cewp-fake-codex-"));
  const scriptPath = path.join(fakeRoot, "fake-codex.js");
  writeFile(scriptPath, `#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");

const args = process.argv.slice(2);
if (args[0] !== "exec") {
  console.error("fake codex only supports exec");
  process.exit(2);
}

function valueAfter(flag) {
  const index = args.indexOf(flag);
  return index === -1 ? undefined : args[index + 1];
}

const worktree = valueAfter("--cd");
const lastMessage = valueAfter("--output-last-message");
const prompt = args[args.length - 1] || "";
const mode = process.env.CEWP_FAKE_CODEX_MODE || "pass";
const roleMatch = prompt.match(/^Role:\\s*(worker-a|worker-b)\\b/m);
const taskMatch = prompt.match(/^Task:\\s*([^\\s]+)\\b/m);
const isReviewer = prompt.includes("CEWP Dispatch Prompt - Reviewer");
const role = isReviewer ? "reviewer" : roleMatch ? roleMatch[1] : "worker-a";
const task = taskMatch ? taskMatch[1] : "unknown-task";
const changedFile = role === "worker-b" ? "docs/install.md" : "README.md";

if (isReviewer) {
  const reportPath = path.join(worktree, "reviews", "reviewer-report.md");
  const eventPath = path.join(worktree, "events", "reviewer.jsonl");
  const decisionValue = mode === "reviewer-request-changes" ? "REQUEST_CHANGES" : "PASS";
  const decisionLine = mode === "reviewer-missing-decision" ? "" : \`Decision: \${decisionValue}\\n\\n\`;
  const decision = mode === "reviewer-missing-decision" ? "not_found" : decisionValue;
  fs.mkdirSync(path.dirname(reportPath), { recursive: true });
  fs.mkdirSync(path.dirname(eventPath), { recursive: true });
  fs.writeFileSync(
    reportPath,
    \`# Reviewer Report\\n\\n\${decisionLine}## Scope Check\\nFake reviewer checked worker outputs.\\n\\n## Forbidden File Check\\nNo forbidden files detected.\\n\\n## Diff Review\\nFake reviewer lifecycle smoke.\\n\\n## Verification\\nHarness fake reviewer completed.\\n\\n## Required Changes\\nNone.\\n\\n## Notes\\nGenerated by harness fake codex.\\n\`,
  );
  fs.writeFileSync(
    eventPath,
    JSON.stringify({ role, event: "fake-reviewer-completed", decision }) + "\\n",
  );

  if (lastMessage) {
    fs.mkdirSync(path.dirname(lastMessage), { recursive: true });
    fs.writeFileSync(lastMessage, \`Fake reviewer completed with decision \${decision}.\\n\`);
  }

  console.log(\`fake codex stdout: reviewer \${decision}\`);
  console.error(\`fake codex stderr: reviewer \${decision}\`);
  process.exit(0);
}

const shouldViolateScope = mode === "scope-violation" && role === "worker-a";
const shouldExitNonZero = mode === "worker-nonzero" && role === "worker-a";
const workerChangedFile = shouldViolateScope ? "secret.txt" : changedFile;

fs.mkdirSync(path.dirname(path.join(worktree, workerChangedFile)), { recursive: true });
fs.writeFileSync(path.join(worktree, workerChangedFile), \`# Fake Codex \${role}\\n\\nTask \${task} changed \${workerChangedFile}.\\n\`);

const outputRoot = path.join(worktree, ".cewp-worker-output");
fs.mkdirSync(outputRoot, { recursive: true });
fs.writeFileSync(
  path.join(outputRoot, \`\${role}-report.md\`),
  \`# Worker Report\\n\\nRole: \${role}\\nTask: \${task}\\nStatus: ready_for_review\\n\\n## Summary\\nFake codex lifecycle smoke.\\n\\n## Changed Files\\n- \${workerChangedFile}\\n\\n## Commands Run\\n- fake codex exec\\n\\n## Test Results\\n- not run by fake shim\\n\\n## Risks\\n- none\\n\\n## Handoff Notes\\n- generated by harness fake codex\\n\`,
);
fs.writeFileSync(
  path.join(outputRoot, \`\${role}-events.jsonl\`),
  JSON.stringify({ role, task, event: "fake-codex-completed", changedFile: workerChangedFile }) + "\\n",
);

if (lastMessage) {
  fs.mkdirSync(path.dirname(lastMessage), { recursive: true });
  fs.writeFileSync(lastMessage, \`Fake codex completed \${role} for \${task}.\\n\`);
}

console.log(\`fake codex stdout: \${role} \${task}\`);
console.error(\`fake codex stderr: \${role} \${task}\`);
if (shouldExitNonZero) {
  process.exit(7);
}
`);

  return {
    fakeRoot,
    mode,
    env: {
      ...process.env,
      CEWP_FAKE_CODEX_MODE: mode,
      CEWP_CODEX_EXEC_COMMAND: process.execPath,
      CEWP_CODEX_EXEC_PREFIX_ARGS: JSON.stringify([scriptPath]),
    },
  };
}

function createFakeOpenCodeAdapter(mode = FAKE_OPENCODE_MODES.PASS) {
  const fakeRoot = fs.mkdtempSync(path.join(os.tmpdir(), "cewp-fake-opencode-"));
  const scriptPath = path.join(fakeRoot, "fake-opencode.js");
  writeFile(scriptPath, `#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");

const args = process.argv.slice(2);

if (args[0] === "--version") {
  console.log("fake-opencode 0.0.0");
  process.exit(0);
}

if (args[0] !== "run") {
  console.error("fake opencode only supports run");
  process.exit(2);
}

function valueAfter(flag) {
  const index = args.indexOf(flag);
  return index === -1 ? undefined : args[index + 1];
}

const worktree = valueAfter("--dir");
const format = valueAfter("--format");
const prompt = args[args.length - 1] || "";
const mode = process.env.CEWP_FAKE_OPENCODE_MODE || "pass";
const roleMatch = prompt.match(/^Role:\\s*(worker-a|worker-b)\\b/m);
const taskMatch = prompt.match(/^Task:\\s*([^\\s]+)\\b/m);
const role = roleMatch ? roleMatch[1] : "worker-a";
const task = taskMatch ? taskMatch[1] : "unknown-task";
const changedFile = role === "worker-b" ? "docs/install.md" : "README.md";

if (!worktree || format !== "json") {
  console.error("fake opencode requires --dir <worktree> --format json");
  process.exit(2);
}

if (mode === "timeout") {
  setTimeout(() => {}, 10000);
  return;
}

if (mode === "silent-nonzero") {
  process.exit(1);
}

fs.mkdirSync(path.dirname(path.join(worktree, changedFile)), { recursive: true });
fs.writeFileSync(path.join(worktree, changedFile), \`# Fake OpenCode \${role}\\n\\nTask \${task} changed \${changedFile}.\\n\`);

const outputRoot = path.join(worktree, ".cewp-worker-output");
fs.mkdirSync(outputRoot, { recursive: true });
fs.writeFileSync(
  path.join(outputRoot, \`\${role}-report.md\`),
  \`# Worker Report\\n\\nRole: \${role}\\nTask: \${task}\\nStatus: ready_for_review\\n\\n## Summary\\nFake OpenCode lifecycle smoke.\\n\\n## Changed Files\\n- \${changedFile}\\n\\n## Commands Run\\n- fake opencode run\\n\\n## Test Results\\n- not run by fake shim\\n\\n## Risks\\n- none\\n\\n## Handoff Notes\\n- generated by harness fake opencode\\n\`,
);
fs.writeFileSync(
  path.join(outputRoot, \`\${role}-events.jsonl\`),
  JSON.stringify({ role, task, event: "fake-opencode-completed", changedFile }) + "\\n",
);

if (mode === "invalid-json") {
  console.log("{ invalid opencode json");
  console.error(\`fake opencode stderr: invalid json \${role} \${task}\`);
  process.exit(0);
}

if (mode === "unexpected-json") {
  console.log(JSON.stringify({ type: "done", metrics: { ok: true, role, task } }));
  console.error(\`fake opencode stderr: unexpected json \${role} \${task}\`);
  process.exit(0);
}

console.log(JSON.stringify({ type: "message", role, task, content: \`Fake OpenCode completed \${role} for \${task}.\` }));
console.log(JSON.stringify({ type: "result", role, task, summary: \`Fake OpenCode result for \${role}.\` }));
console.error(\`fake opencode stderr: \${role} \${task}\`);

if (mode === "nonzero") {
  process.exit(7);
}
`);

  return {
    fakeRoot,
    mode,
    scriptPath,
    env: {
      ...process.env,
      CEWP_FAKE_OPENCODE_MODE: mode,
      CEWP_OPENCODE_COMMAND: process.execPath,
      CEWP_OPENCODE_PREFIX_ARGS: JSON.stringify([scriptPath]),
    },
  };
}

module.exports = {
  FAKE_ADAPTER_MODES,
  FAKE_OPENCODE_MODES,
  createFakeCodexAdapter,
  createFakeOpenCodeAdapter,
};
