"use strict";

const fs = require("node:fs");
const path = require("node:path");
const { readJsonIfExists } = require("../../lib/json");
const { isGitWorktreePath } = require("../../lib/git");
const { getWorktreeChangeSummary } = require("../../lib/scope-check");
const { findRun, readWorktreesRegistry } = require("../runtime-cleanup");
const {
  relativeRunPath,
  getPromptPath,
  getDispatchWorktree,
  checkLabel,
  overallDispatchStatus,
  addDispatchCheck,
  shouldIgnorePromptMissingForPipeline,
  getTaskReadinessStatus,
  getTaskBranch,
  readTasks,
} = require("./shared");
const { getManagedWorktreesRoot, isPathInside } = require("../worktrees");

function runDispatchCheck(options = {}) {
  const { runId, runRoot } = findRun(options);
  const runJson = readJsonIfExists(path.join(runRoot, "run.json"));
  const boardJson = readJsonIfExists(path.join(runRoot, "board.json"));
  const taskEntries = readTasks(runRoot);
  const worktreesRegistry = readWorktreesRegistry(runRoot);
  const checks = [];
  const taskReadiness = [];
  const supportedWorkers = ["worker-a", "worker-b"];
  const repoRoot = (runJson && runJson.repoRoot) || process.cwd();
  const managedWorktreesRoot = getManagedWorktreesRoot(repoRoot);

  if (runJson) {
    addDispatchCheck(checks, "ok", "run.json found");
  } else {
    addDispatchCheck(checks, "fail", "run.json missing");
  }

  if (boardJson) {
    addDispatchCheck(checks, "ok", "board.json found");
  } else {
    addDispatchCheck(checks, "fail", "board.json missing");
  }

  if (taskEntries.length > 0) {
    addDispatchCheck(checks, "ok", `tasks found: ${taskEntries.length}`);
  } else {
    addDispatchCheck(checks, "fail", "tasks not found. Ask the Manager to create tasks first.");
  }

  if (worktreesRegistry) {
    addDispatchCheck(checks, "ok", "worktrees registry found");
  } else {
    addDispatchCheck(checks, "fail", "worktrees.json missing. Run cewp run worktrees create before dispatch.");
  }

  if ((runJson && runJson.reviewer) || (boardJson && boardJson.roles && boardJson.roles.reviewer)) {
    addDispatchCheck(checks, "ok", "reviewer role configured");
  } else {
    addDispatchCheck(checks, "fail", "reviewer role missing from run/board state");
  }

  for (const role of supportedWorkers) {
    const promptPath = getPromptPath(runRoot, role);
    const ignorePromptMissing = shouldIgnorePromptMissingForPipeline(options, promptPath, role, runRoot);
    addDispatchCheck(
      checks,
      fs.existsSync(promptPath) || ignorePromptMissing ? "ok" : "fail",
      `${role} prompt ${fs.existsSync(promptPath) ? "found" : ignorePromptMissing ? "will be generated by dispatch prompts" : `missing: ${relativeRunPath(runRoot, promptPath)}`}`,
    );
  }

  const reviewerPromptPath = getPromptPath(runRoot, "reviewer");
  const ignoreReviewerPromptMissing = shouldIgnorePromptMissingForPipeline(options, reviewerPromptPath, "reviewer", runRoot);
  addDispatchCheck(
    checks,
    fs.existsSync(reviewerPromptPath) || ignoreReviewerPromptMissing ? "ok" : "fail",
    `reviewer prompt ${fs.existsSync(reviewerPromptPath) ? "found" : ignoreReviewerPromptMissing ? "will be generated by dispatch prompts" : `missing: ${relativeRunPath(runRoot, reviewerPromptPath)}`}`,
  );

  const reviewPacketPath = path.join(runRoot, "review-packets", "review-packet.md");
  addDispatchCheck(
    checks,
    fs.existsSync(reviewPacketPath) ? "ok" : "warn",
    fs.existsSync(reviewPacketPath)
      ? "review packet found"
      : `review packet missing: ${relativeRunPath(runRoot, reviewPacketPath)}`,
  );

  const reviewerReportPath = path.join(runRoot, "reviews", "reviewer-report.md");
  const reviewerEventPath = path.join(runRoot, "events", "reviewer.jsonl");
  addDispatchCheck(checks, "ok", `reviewer output path ready: ${relativeRunPath(runRoot, reviewerReportPath)}`);
  addDispatchCheck(checks, "ok", `reviewer event path ready: ${relativeRunPath(runRoot, reviewerEventPath)}`);

  for (const { task } of taskEntries) {
    const taskId = task.id || "unknown-task";
    const levels = [];
    const addTaskLevel = (level) => levels.push(level);
    const worktree = getDispatchWorktree(worktreesRegistry, task.id);
    const assignedRole = task.assignedRole;

    if (task.id) {
      addDispatchCheck(checks, "ok", `${taskId} task id found`);
      addTaskLevel("ok");
    } else {
      addDispatchCheck(checks, "fail", "task file missing required id");
      addTaskLevel("fail");
    }

    if (assignedRole) {
      addDispatchCheck(checks, "ok", `${taskId} assignedRole: ${assignedRole}`);
      addTaskLevel("ok");
    } else {
      addDispatchCheck(checks, "fail", `${taskId} assignedRole missing`);
      addTaskLevel("fail");
    }

    if (assignedRole && supportedWorkers.includes(assignedRole)) {
      addDispatchCheck(checks, "ok", `${taskId} assignedRole supported`);
      addTaskLevel("ok");
    } else if (assignedRole) {
      addDispatchCheck(checks, "fail", `${taskId} assignedRole unsupported: ${assignedRole}`);
      addTaskLevel("fail");
    }

    try {
      const branch = task.id ? getTaskBranch(task, runId) : undefined;
      if (branch) {
        addDispatchCheck(checks, "ok", `${taskId} branch ready: ${branch}`);
        addTaskLevel("ok");
      }
    } catch (error) {
      addDispatchCheck(checks, "fail", `${taskId} branch invalid: ${error.message}`);
      addTaskLevel("fail");
    }

    if (worktree) {
      addDispatchCheck(checks, "ok", `${taskId} matching worktree registry entry found`);
      addTaskLevel("ok");
    } else {
      addDispatchCheck(checks, "fail", `${taskId} matching worktree registry entry missing`);
      addTaskLevel("fail");
    }

    if (worktree && worktree.path) {
      addDispatchCheck(checks, "ok", `${taskId} worktree path registered`);
      addTaskLevel("ok");

      if (isPathInside(managedWorktreesRoot, worktree.path)) {
        addDispatchCheck(checks, "ok", `${taskId} worktree path is under CEWP-managed root`);
        addTaskLevel("ok");
      } else {
        addDispatchCheck(checks, "fail", `${taskId} worktree path is outside CEWP-managed root: ${worktree.path}`);
        addTaskLevel("fail");
      }

      if (fs.existsSync(worktree.path)) {
        addDispatchCheck(checks, "ok", `${taskId} worktree path exists`);
        addTaskLevel("ok");

        if (isGitWorktreePath(worktree.path)) {
          addDispatchCheck(checks, "ok", `${taskId} path is a git worktree`);
          addTaskLevel("ok");

          const changeSummary = getWorktreeChangeSummary(worktree.path, worktree.baseCommit);
          if (changeSummary.statusLines.length > 0) {
            addDispatchCheck(checks, "warn", `${taskId} worktree is dirty`);
            addTaskLevel("warn");
          } else {
            addDispatchCheck(checks, "ok", `${taskId} worktree is clean`);
            addTaskLevel("ok");
          }

          if (changeSummary.missingBaseCommit) {
            addDispatchCheck(checks, "fail", `${taskId} worktree registry missing baseCommit; committed diff check cannot run`);
            addTaskLevel("fail");
          } else if (changeSummary.committedDiffError) {
            addDispatchCheck(checks, "fail", `${taskId} committed diff check failed: ${changeSummary.committedDiffError.message}`);
            addTaskLevel("fail");
          } else {
            addDispatchCheck(checks, "ok", `${taskId} committed diff check ready`);
            addTaskLevel("ok");
          }
        } else {
          addDispatchCheck(checks, "fail", `${taskId} path is not a git worktree: ${worktree.path}`);
          addTaskLevel("fail");
        }
      } else {
        addDispatchCheck(checks, "fail", `${taskId} worktree path missing: ${worktree.path}`);
        addTaskLevel("fail");
      }
    } else if (worktree) {
      addDispatchCheck(checks, "fail", `${taskId} worktree path missing`);
      addTaskLevel("fail");
    }

    const promptPath = assignedRole ? getPromptPath(runRoot, assignedRole) : undefined;
    if (promptPath && (fs.existsSync(promptPath) || shouldIgnorePromptMissingForPipeline(options, promptPath, assignedRole, runRoot))) {
      addDispatchCheck(checks, "ok", `${taskId} prompt file ${fs.existsSync(promptPath) ? "found" : "will be generated by dispatch prompts"}`);
      addTaskLevel("ok");
    } else {
      addDispatchCheck(checks, "fail", `${taskId} prompt file missing`);
      addTaskLevel("fail");
    }

    const reportPath = assignedRole ? path.join(runRoot, "reports", `${assignedRole}-report.md`) : undefined;
    const eventPath = assignedRole ? path.join(runRoot, "events", `${assignedRole}.jsonl`) : undefined;
    addDispatchCheck(checks, reportPath ? "ok" : "fail", `${taskId} report path ${reportPath ? "ready" : "not computable"}`);
    addDispatchCheck(checks, eventPath ? "ok" : "fail", `${taskId} event path ${eventPath ? "ready" : "not computable"}`);
    addTaskLevel(reportPath ? "ok" : "fail");
    addTaskLevel(eventPath ? "ok" : "fail");

    if (Array.isArray(task.allowedFiles) && task.allowedFiles.length > 0) {
      addDispatchCheck(checks, "ok", `${taskId} allowedFiles configured`);
      addTaskLevel("ok");
    } else if (assignedRole && supportedWorkers.includes(assignedRole)) {
      addDispatchCheck(checks, "fail", `${taskId} allowedFiles is empty; real worker execution requires an explicit file scope`);
      addTaskLevel("fail");
    } else {
      addDispatchCheck(checks, "warn", `${taskId} allowedFiles is empty`);
      addTaskLevel("warn");
    }

    if (Array.isArray(task.forbiddenFiles) && task.forbiddenFiles.length > 0) {
      addDispatchCheck(checks, "ok", `${taskId} forbiddenFiles configured`);
      addTaskLevel("ok");
    } else {
      addDispatchCheck(checks, "warn", `${taskId} forbiddenFiles is empty`);
      addTaskLevel("warn");
    }

    taskReadiness.push({
      taskId,
      assignedRole: assignedRole || "unassigned",
      status: getTaskReadinessStatus(levels),
    });
  }

  const reviewerLevels = [];
  reviewerLevels.push(fs.existsSync(reviewerPromptPath) || ignoreReviewerPromptMissing ? "ok" : "fail");
  reviewerLevels.push(fs.existsSync(reviewPacketPath) ? "ok" : "warn");
  reviewerLevels.push(reviewerReportPath ? "ok" : "fail");
  reviewerLevels.push(reviewerEventPath ? "ok" : "fail");

  const status = overallDispatchStatus(checks);

  console.log("CEWP Coordinator Mode dispatch check");
  console.log(`Run ID: ${runId}`);
  console.log(`Run root: ${runRoot}`);
  console.log("");
  console.log(`Status: ${status}`);
  console.log("");

  console.log("Checks:");
  for (const check of checks) {
    console.log(`  [${checkLabel(check.level)}] ${check.message}`);
  }
  console.log("");

  console.log("Task readiness:");
  if (taskReadiness.length === 0) {
    console.log("  none");
  } else {
    for (const task of taskReadiness) {
      console.log(`  ${task.taskId} / ${task.assignedRole}: ${task.status}`);
    }
  }
  console.log("");

  console.log("Reviewer readiness:");
  console.log(`  reviewer: ${getTaskReadinessStatus(reviewerLevels)}`);
  console.log(`    Output: ${relativeRunPath(runRoot, reviewerReportPath)}`);
  console.log(`    Event log: ${relativeRunPath(runRoot, reviewerEventPath)}`);
  console.log("");

  console.log("Next:");
  if (status === "FAIL") {
    console.log("  Fix FAIL checks before worker dispatch.");
  } else {
    console.log("  If PASS, worker dispatch can be considered after user approval.");
    console.log("  WARN items should be reviewed before dispatch.");
  }
  console.log("  This command did not start agents.");

  if (status === "FAIL") {
    process.exitCode = 1;
  }

  return status;
}

module.exports = {
  runDispatchCheck,
};
